version: 1
user: cvmfsunpacker
cvmfs_repo: 'unpacked.cern.ch'
output_format: 'https://gitlab-registry.cern.ch/unpacked/sync/$(image)'
input:
    - 'https://registry.hub.docker.com/library/centos:centos7'
    - 'https://registry.hub.docker.com/engineren/ilcsoft:test'
    - 'https://registry.hub.docker.com/uegede/weather:latest'
    - 'https://registry.hub.docker.com/ville761/af2:latest'
    - 'https://registry.hub.docker.com/dseitova/bars-image:v2'
    - 'https://registry.hub.docker.com/stimela/cubicalddf:1.4.6'
    - 'https://registry.hub.docker.com/stimela/breizorro:1.7.1'
    - 'https://registry.hub.docker.com/stimela/ddfacet:1.7.0'
    - 'https://registry.hub.docker.com/stimela/montage:1.7.1-dev'
    - 'https://registry.hub.docker.com/stimela/cubical:1.6.7'
    - 'https://registry.hub.docker.com/stimela/rm-tools:1.6.9-1'
    - 'https://registry.hub.docker.com/stimela/ragavi:1.7.3'
    - 'https://registry.hub.docker.com/stimela/shadems:1.7.1'
    - 'https://registry.hub.docker.com/stimela/owlcat:1.6.6'
    - 'https://registry.hub.docker.com/stimela/pybdsf:1.6.6'
    - 'https://registry.hub.docker.com/stimela/pybdsf:1.6.6'
    - 'https://quay.io/stimela/aegean:v1.1.3'
    - 'https://quay.io/stimela/wsclean:1.7.7'
    - 'https://quay.io/stimela/cubical:1.7.7'
    - 'https://quay.io/stimela/meqtrees:1.7.2'
    - 'https://gitlab-p4n.aip.de:5005/compute4punch/container-stacks/htcondor-wn:latest'
    - 'https://gitlab-p4n.aip.de:5005/compute4punch/container-stacks/wlcg-wn:latest'
    - 'https://gitlab-p4n.aip.de:5005/compute4punch/container-stacks/linc-wn:latest'
    - 'https://gitlab-p4n.aip.de:5005/compute4punch/container-stacks/h4leptons:latest'
    - 'https://gitlab-p4n.aip.de:5005/compute4punch/container-stacks/snakemake_arcane:latest'
    - 'https://gitlab-p4n.aip.de:5005/compute4punch/container-stacks/snakemake-wn:latest'
    - 'https://gitlab-p4n.aip.de:5005/compute4punch/container-stacks/caracal_container:latest'
    - 'https://gitlab-p4n.aip.de:5005/compute4punch/container-stacks/caracal_container_new_stimela:latest'
    - 'https://gitlab-p4n.aip.de:5005/compute4punch/container-stacks/lqcd_analysis:latest'
    - 'https://registry.hub.docker.com/augerobservatory/offline:latest'
    - 'https://registry.hub.docker.com/augerobservatory/augerdev:latest'
